(() => {
  const translations = {
    en: {
      tagline:'Choose the road that suits you', language:'Language', eyebrow:'Your next lane', heading:'Where are you headed?', from:'From', to:'To', fromPlaceholder:'Address or place, e.g. Kufstein, Austria', toPlaceholder:'Destination', swap:'Swap locations ↕', options:'Which route options should we find?', optionsHint:'We always look for the fastest route and available alternatives.', localOption:'Include a local-road option (avoid motorways)', tollOption:'Include an option avoiding toll roads', search:'Find real routes →', ready:'Enter two locations and select Find real routes.', choose:'Choose your route', routeNote:'Scenic views, quiet roads, road surface and toll prices still need additional verified data. We will add those choices when we can score them reliably.', setup:'Mapbox setup', setupHint:'For local testing, paste a Mapbox public token beginning with pk. It stays in this browser session. For public deployment, configure your restricted public token in config.js.', publicToken:'Public access token', saveToken:'Save token', clearToken:'Clear saved token', footnote:'Travel times are estimates. Road exclusions may be overridden when no alternative exists. Check road signs and conditions before driving.', mapPlaceholder:'A real map and route will appear after search.', mapCaption:'Mapbox map · actual route geometry', fastest:'Fastest route', local:'Local-road option', toll:'Avoid-tolls option', alternative:'Alternative route {n}', minutes:'{n} min', kilometers:'{n} km', longer:'{n} min longer than fastest. ', preference:'Requested route preference; check the road on the map.', another:'Another route provided by Mapbox.', fastestDetail:'Shortest estimated travel time of these options.', selected:'Selected ✓', show:'Show on map →', mapError:'Map error: {error}', mapLoadError:'The map library could not load. Check your connection.', checkToken:'Check the public token.', requestFailed:'Mapbox request failed ({status}).', notFound:'Location not found: {place}', addToken:'Add a Mapbox public token to search real routes.', finding:'Finding places and routes…', noRoutes:'No driving route was found.', routeCount:'{n} distinct route(s) found.{failed} Select one to compare.', failedRequests:' {n} route request(s) failed.', searchFailed:'Route search failed.', invalidToken:'Use a Mapbox public token that starts with pk.', savedToken:'Public token saved for this browser session. You can now search.', clearedToken:'Browser token cleared.'
    },
    de: {
      tagline:'Wähle die Strecke, die zu dir passt', language:'Sprache', eyebrow:'Deine nächste Route', heading:'Wohin soll es gehen?', from:'Von', to:'Nach', fromPlaceholder:'Adresse oder Ort, z. B. Kufstein, Österreich', toPlaceholder:'Ziel', swap:'Start und Ziel tauschen ↕', options:'Welche Strecken sollen wir suchen?', optionsHint:'Wir suchen immer die schnellste Strecke und verfügbare Alternativen.', localOption:'Landstraßen einbeziehen (Autobahnen vermeiden)', tollOption:'Strecken ohne Maut einbeziehen', search:'Echte Strecken finden →', ready:'Gib Start und Ziel ein und suche nach Strecken.', choose:'Wähle deine Strecke', routeNote:'Für schöne Aussicht, wenig Verkehr, Straßenbelag und Mautpreise brauchen wir zusätzliche verlässliche Daten. Diese Optionen folgen später.', setup:'Mapbox einrichten', setupHint:'Zum lokalen Test einen öffentlichen Mapbox-Token einfügen, der mit pk. beginnt. Er bleibt nur in dieser Browsersitzung. Für die Veröffentlichung den eingeschränkten Token in config.js eintragen.', publicToken:'Öffentlicher Zugriffstoken', saveToken:'Token speichern', clearToken:'Token löschen', footnote:'Fahrzeiten sind Schätzungen. Ausgeschlossene Straßentypen können mangels Alternative trotzdem vorkommen. Beachte Schilder und Straßenverhältnisse.', mapPlaceholder:'Nach der Suche erscheinen Karte und Strecke.', mapCaption:'Mapbox-Karte · tatsächlicher Streckenverlauf', fastest:'Schnellste Strecke', local:'Landstraßen-Option', toll:'Option ohne Maut', alternative:'Alternative Strecke {n}', minutes:'{n} Min.', kilometers:'{n} km', longer:'{n} Min. länger als die schnellste Strecke. ', preference:'Straßenpräferenz angefragt; prüfe den Verlauf auf der Karte.', another:'Weitere Strecke von Mapbox.', fastestDetail:'Kürzeste geschätzte Fahrzeit dieser Optionen.', selected:'Ausgewählt ✓', show:'Auf Karte zeigen →', mapError:'Kartenfehler: {error}', mapLoadError:'Die Kartenbibliothek konnte nicht geladen werden. Prüfe die Verbindung.', checkToken:'Prüfe den öffentlichen Token.', requestFailed:'Mapbox-Anfrage fehlgeschlagen ({status}).', notFound:'Ort nicht gefunden: {place}', addToken:'Füge einen öffentlichen Mapbox-Token hinzu.', finding:'Suche Orte und Strecken…', noRoutes:'Keine Autostrecke gefunden.', routeCount:'{n} unterschiedliche Strecke(n) gefunden.{failed} Wähle eine zum Vergleichen.', failedRequests:' {n} Streckenanfrage(n) fehlgeschlagen.', searchFailed:'Streckensuche fehlgeschlagen.', invalidToken:'Verwende einen öffentlichen Mapbox-Token, der mit pk. beginnt.', savedToken:'Token für diese Browsersitzung gespeichert. Du kannst jetzt suchen.', clearedToken:'Gespeicherter Token gelöscht.'
    },
    it: {
      tagline:'Scegli la strada adatta a te', language:'Lingua', eyebrow:'Il tuo prossimo percorso', heading:'Dove vuoi andare?', from:'Da', to:'A', fromPlaceholder:'Indirizzo o luogo, es. Kufstein, Austria', toPlaceholder:'Destinazione', swap:'Scambia partenza e arrivo ↕', options:'Quali percorsi cerchiamo?', optionsHint:'Cerchiamo sempre il percorso più veloce e le alternative disponibili.', localOption:'Includi strade locali (evita autostrade)', tollOption:'Includi percorsi senza pedaggio', search:'Trova percorsi reali →', ready:'Inserisci partenza e destinazione, poi cerca.', choose:'Scegli il tuo percorso', routeNote:'Paesaggi, traffico tranquillo, fondo stradale e costi dei pedaggi richiedono dati aggiuntivi verificati. Aggiungeremo queste scelte in seguito.', setup:'Impostazioni Mapbox', setupHint:'Per provare in locale, inserisci un token pubblico Mapbox che inizi con pk. Resta solo in questa sessione. Per la pubblicazione, configura il token limitato in config.js.', publicToken:'Token di accesso pubblico', saveToken:'Salva token', clearToken:'Cancella token', footnote:'I tempi sono stimati. Se non ci sono alternative, alcune strade escluse possono essere usate. Rispetta la segnaletica e le condizioni stradali.', mapPlaceholder:'La mappa e il percorso appariranno dopo la ricerca.', mapCaption:'Mappa Mapbox · percorso reale', fastest:'Percorso più veloce', local:'Strade locali', toll:'Senza pedaggio', alternative:'Percorso alternativo {n}', minutes:'{n} min', kilometers:'{n} km', longer:'{n} min in più del più veloce. ', preference:'Preferenza richiesta; verifica la strada sulla mappa.', another:'Un altro percorso fornito da Mapbox.', fastestDetail:'Tempo di viaggio stimato più breve tra queste opzioni.', selected:'Selezionato ✓', show:'Mostra sulla mappa →', mapError:'Errore mappa: {error}', mapLoadError:'Impossibile caricare la mappa. Controlla la connessione.', checkToken:'Controlla il token pubblico.', requestFailed:'Richiesta Mapbox non riuscita ({status}).', notFound:'Luogo non trovato: {place}', addToken:'Aggiungi un token pubblico Mapbox per cercare percorsi.', finding:'Ricerca di luoghi e percorsi…', noRoutes:'Nessun percorso in auto trovato.', routeCount:'{n} percorsi distinti trovati.{failed} Scegline uno da confrontare.', failedRequests:' {n} richieste di percorso non riuscite.', searchFailed:'Ricerca del percorso non riuscita.', invalidToken:'Usa un token pubblico Mapbox che inizi con pk.', savedToken:'Token salvato per questa sessione. Ora puoi cercare.', clearedToken:'Token salvato cancellato.'
    },
    fr: {
      tagline:'Choisissez la route qui vous convient', language:'Langue', eyebrow:'Votre prochain trajet', heading:'Où allez-vous ?', from:'Départ', to:'Arrivée', fromPlaceholder:'Adresse ou lieu, ex. Kufstein, Autriche', toPlaceholder:'Destination', swap:'Inverser départ et arrivée ↕', options:'Quels trajets rechercher ?', optionsHint:'Nous cherchons toujours le trajet le plus rapide et les alternatives disponibles.', localOption:'Inclure une route locale (éviter les autoroutes)', tollOption:'Inclure une route sans péage', search:'Trouver des trajets réels →', ready:'Saisissez le départ et l’arrivée, puis lancez la recherche.', choose:'Choisissez votre trajet', routeNote:'Les beaux paysages, les routes calmes, le revêtement et les tarifs de péage nécessitent des données fiables supplémentaires. Nous ajouterons ces choix ensuite.', setup:'Configuration Mapbox', setupHint:'Pour tester en local, collez un jeton public Mapbox commençant par pk. Il reste dans cette session. Pour publier, renseignez le jeton limité dans config.js.', publicToken:'Jeton d’accès public', saveToken:'Enregistrer le jeton', clearToken:'Effacer le jeton', footnote:'Les durées sont estimées. Sans alternative, un type de route exclu peut être emprunté. Respectez la signalisation et les conditions de circulation.', mapPlaceholder:'La carte et le trajet apparaîtront après la recherche.', mapCaption:'Carte Mapbox · tracé réel', fastest:'Trajet le plus rapide', local:'Option routes locales', toll:'Option sans péage', alternative:'Trajet alternatif {n}', minutes:'{n} min', kilometers:'{n} km', longer:'{n} min de plus que le plus rapide. ', preference:'Préférence demandée ; vérifiez le trajet sur la carte.', another:'Autre trajet fourni par Mapbox.', fastestDetail:'Durée estimée la plus courte parmi ces options.', selected:'Sélectionné ✓', show:'Afficher sur la carte →', mapError:'Erreur de carte : {error}', mapLoadError:'Impossible de charger la carte. Vérifiez la connexion.', checkToken:'Vérifiez le jeton public.', requestFailed:'Échec de la requête Mapbox ({status}).', notFound:'Lieu introuvable : {place}', addToken:'Ajoutez un jeton public Mapbox pour chercher des trajets.', finding:'Recherche des lieux et trajets…', noRoutes:'Aucun trajet en voiture trouvé.', routeCount:'{n} trajet(s) distinct(s) trouvé(s).{failed} Choisissez-en un.', failedRequests:' {n} requête(s) de trajet ont échoué.', searchFailed:'Échec de la recherche.', invalidToken:'Utilisez un jeton public Mapbox commençant par pk.', savedToken:'Jeton enregistré pour cette session. Vous pouvez chercher.', clearedToken:'Jeton enregistré effacé.'
    },
    nl: {
      tagline:'Kies de weg die bij je past', language:'Taal', eyebrow:'Je volgende route', heading:'Waar ga je heen?', from:'Van', to:'Naar', fromPlaceholder:'Adres of plaats, bijv. Kufstein, Oostenrijk', toPlaceholder:'Bestemming', swap:'Vertrek en bestemming wisselen ↕', options:'Welke routes zoeken we?', optionsHint:'We zoeken altijd de snelste route en beschikbare alternatieven.', localOption:'Lokale wegen meenemen (snelwegen vermijden)', tollOption:'Routes zonder tol meenemen', search:'Echte routes zoeken →', ready:'Vul vertrek en bestemming in en zoek routes.', choose:'Kies je route', routeNote:'Voor mooie uitzichten, rustige wegen, wegdek en tolprijzen zijn extra betrouwbare gegevens nodig. Deze keuzes voegen we later toe.', setup:'Mapbox instellen', setupHint:'Plak voor lokaal testen een publieke Mapbox-token die met pk. begint. Deze blijft alleen in deze browsersessie. Voor publicatie stel je de beperkte token in config.js in.', publicToken:'Publieke toegangstoken', saveToken:'Token opslaan', clearToken:'Token wissen', footnote:'Reistijden zijn schattingen. Als er geen alternatief is, kan een uitgesloten wegtype toch voorkomen. Let op borden en wegomstandigheden.', mapPlaceholder:'Na het zoeken verschijnen kaart en route.', mapCaption:'Mapbox-kaart · werkelijk routeverloop', fastest:'Snelste route', local:'Lokale wegen', toll:'Zonder tol', alternative:'Alternatieve route {n}', minutes:'{n} min', kilometers:'{n} km', longer:'{n} min langer dan de snelste. ', preference:'Wegvoorkeur aangevraagd; controleer de route op de kaart.', another:'Andere route van Mapbox.', fastestDetail:'Kortste geschatte reistijd van deze opties.', selected:'Geselecteerd ✓', show:'Toon op kaart →', mapError:'Kaartfout: {error}', mapLoadError:'De kaart kon niet worden geladen. Controleer je verbinding.', checkToken:'Controleer de publieke token.', requestFailed:'Mapbox-verzoek mislukt ({status}).', notFound:'Plaats niet gevonden: {place}', addToken:'Voeg een publieke Mapbox-token toe om routes te zoeken.', finding:'Plaatsen en routes zoeken…', noRoutes:'Geen autoroute gevonden.', routeCount:'{n} verschillende route(s) gevonden.{failed} Kies er een om te vergelijken.', failedRequests:' {n} routeverzoek(en) mislukt.', searchFailed:'Routes zoeken mislukt.', invalidToken:'Gebruik een publieke Mapbox-token die begint met pk.', savedToken:'Token opgeslagen voor deze browsersessie. Je kunt nu zoeken.', clearedToken:'Opgeslagen token gewist.'
    },
    fa: {
      tagline:'مسیر مناسب خودت را انتخاب کن', language:'زبان', eyebrow:'مسیر بعدی تو', heading:'کجا می‌خواهی بروی؟', from:'مبدأ', to:'مقصد', fromPlaceholder:'آدرس یا شهر، مثلاً Kufstein, Austria', toPlaceholder:'مقصد را بنویس', swap:'جابه‌جایی مبدأ و مقصد ↕', options:'چه مسیرهایی را پیدا کنیم؟', optionsHint:'همیشه سریع‌ترین مسیر و مسیرهای جایگزین موجود را جست‌وجو می‌کنیم.', localOption:'مسیر محلی را هم بیاور (پرهیز از اتوبان)', tollOption:'مسیر بدون عوارض را هم بیاور', search:'پیدا کردن مسیرهای واقعی ←', ready:'مبدأ و مقصد را وارد کن و مسیرها را جست‌وجو کن.', choose:'مسیرت را انتخاب کن', routeNote:'برای منظرهٔ زیبا، راه خلوت، کیفیت جاده و هزینهٔ عوارض به دادهٔ معتبر بیشتری نیاز داریم. این انتخاب‌ها را بعداً اضافه می‌کنیم.', setup:'تنظیمات Mapbox', setupHint:'برای آزمایش، توکن عمومی Mapbox را که با pk. شروع می‌شود وارد کن. فقط در همین نشست مرورگر می‌ماند. برای انتشار عمومی، توکن محدودشده را در config.js تنظیم کن.', publicToken:'توکن دسترسی عمومی', saveToken:'ذخیرهٔ توکن', clearToken:'پاک کردن توکن', footnote:'زمان‌ها تخمینی‌اند. اگر مسیر جایگزینی نباشد، ممکن است جادهٔ مستثناشده هم استفاده شود. به تابلوها و وضعیت جاده توجه کن.', mapPlaceholder:'بعد از جست‌وجو، نقشه و مسیر واقعی نشان داده می‌شوند.', mapCaption:'نقشهٔ Mapbox · مسیر واقعی', fastest:'سریع‌ترین مسیر', local:'گزینهٔ مسیر محلی', toll:'گزینهٔ بدون عوارض', alternative:'مسیر جایگزین {n}', minutes:'{n} دقیقه', kilometers:'{n} کیلومتر', longer:'{n} دقیقه طولانی‌تر از سریع‌ترین مسیر. ', preference:'این ترجیح از سرویس درخواست شده؛ مسیر را روی نقشه بررسی کن.', another:'مسیر جایگزین ارائه‌شده توسط Mapbox.', fastestDetail:'کمترین زمان تخمینی بین این گزینه‌ها.', selected:'انتخاب شده ✓', show:'نمایش روی نقشه ←', mapError:'خطای نقشه: {error}', mapLoadError:'نقشه بارگذاری نشد. اتصال اینترنت را بررسی کن.', checkToken:'توکن عمومی را بررسی کن.', requestFailed:'درخواست Mapbox ناموفق بود ({status}).', notFound:'مکان پیدا نشد: {place}', addToken:'برای جست‌وجوی مسیر، توکن عمومی Mapbox را وارد کن.', finding:'در حال پیدا کردن مکان‌ها و مسیرها…', noRoutes:'مسیر رانندگی پیدا نشد.', routeCount:'{n} مسیر متمایز پیدا شد.{failed} یکی را برای مقایسه انتخاب کن.', failedRequests:' {n} درخواست مسیر ناموفق بود.', searchFailed:'جست‌وجوی مسیر ناموفق بود.', invalidToken:'توکن عمومی Mapbox باید با pk. شروع شود.', savedToken:'توکن برای این نشست مرورگر ذخیره شد. حالا می‌توانی جست‌وجو کنی.', clearedToken:'توکن ذخیره‌شده پاک شد.'
    }
  };
  const extra = {
    en:{hero:'A better way to go',intro:'Compare real routes. Pick the journey that feels right.',tripType:'How are you travelling?',drive:'Drive',walk:'Walk',cycle:'Cycle',driveHint:'Traffic-aware routes and road preferences',walkHint:'Paths and sidewalks',cycleHint:'Bike-friendly routes',discover:'Explore routes',compare:'Available routes',save:'Save for later',saved:'Saved trips',savedHere:'Saved on this device',emptySaved:'Your saved trips will appear here.',remove:'Remove',start:'Start now',stop:'Stop trip',tripReady:'Ready to go',tripReadyHint:'Your selected route is highlighted. Save it or start with your current location.',gpsWaiting:'Finding your location…',gpsActive:'Your location is shown on the map. Follow the route and road signs.',gpsDenied:'Location unavailable. Allow location access in your browser settings.',gpsSecure:'Live location requires HTTPS or localhost.',gpsNote:'Live position preview only. No automatic rerouting or spoken guidance yet.',instructions:'Route steps',instructionsFallback:'Route instructions are available in English for this language.',savedMessage:'Trip saved on this device.',removedMessage:'Saved trip removed.',savedLoaded:'Saved route loaded. Check current conditions before travelling.',storageError:'Could not save this trip on this device.',chooseFirst:'Choose a route first.',noExtra:'No other distinct routes were returned for this trip.',refresh:'Search again for current conditions',selectedRoute:'Selected route',arrival:'Arrive at your destination',kmAway:'{n} km from destination',locationError:'Location error: {error}',updated:'Updated {time}',roadNotice:'Road preference requested; the route can still include excluded roads.',navigationInfo:'Select a route, then choose Save for later or Start now.',mapAria:'Route map',savedAria:'Saved routes',resultsAria:'Available routes'},
    de:{hero:'Dein Weg, deine Wahl',intro:'Vergleiche echte Strecken und wähle die Fahrt, die zu dir passt.',tripType:'Wie bist du unterwegs?',drive:'Auto',walk:'Zu Fuß',cycle:'Fahrrad',driveHint:'Verkehr und Straßenwünsche',walkHint:'Wege und Gehsteige',cycleHint:'Fahrradfreundliche Wege',discover:'Strecken entdecken',compare:'Verfügbare Strecken',save:'Für später speichern',saved:'Gespeicherte Fahrten',savedHere:'Auf diesem Gerät gespeichert',emptySaved:'Hier erscheinen deine gespeicherten Fahrten.',remove:'Entfernen',start:'Jetzt starten',stop:'Fahrt beenden',tripReady:'Bereit zur Fahrt',tripReadyHint:'Die gewählte Strecke ist markiert. Speichere sie oder starte mit deinem Standort.',gpsWaiting:'Standort wird ermittelt…',gpsActive:'Dein Standort ist auf der Karte. Folge der Strecke und den Verkehrszeichen.',gpsDenied:'Standort nicht verfügbar. Erlaube den Zugriff in den Browsereinstellungen.',gpsSecure:'Live-Standort erfordert HTTPS oder localhost.',gpsNote:'Nur Live-Standortvorschau. Noch keine automatische Neuberechnung oder Sprachansagen.',instructions:'Wegbeschreibung',instructionsFallback:'Für diese Sprache ist die Wegbeschreibung auf Englisch verfügbar.',savedMessage:'Fahrt auf diesem Gerät gespeichert.',removedMessage:'Gespeicherte Fahrt entfernt.',savedLoaded:'Gespeicherte Strecke geladen. Prüfe vor der Fahrt aktuelle Bedingungen.',storageError:'Fahrt konnte auf diesem Gerät nicht gespeichert werden.',chooseFirst:'Wähle zuerst eine Strecke.',noExtra:'Für diese Fahrt wurden keine weiteren unterschiedlichen Strecken gefunden.',refresh:'Für aktuelle Bedingungen erneut suchen',selectedRoute:'Gewählte Strecke',arrival:'Ziel erreicht',kmAway:'{n} km bis zum Ziel',locationError:'Standortfehler: {error}',updated:'Aktualisiert {time}',roadNotice:'Straßenwunsch angefragt; ausgeschlossene Straßen können dennoch vorkommen.',navigationInfo:'Wähle eine Strecke und dann Speichern oder Jetzt starten.',mapAria:'Streckenkarte',savedAria:'Gespeicherte Strecken',resultsAria:'Verfügbare Strecken'},
    it:{hero:'La strada la scegli tu',intro:'Confronta percorsi reali e scegli il viaggio giusto per te.',tripType:'Come viaggi?',drive:'Auto',walk:'A piedi',cycle:'Bici',driveHint:'Traffico e preferenze stradali',walkHint:'Sentieri e marciapiedi',cycleHint:'Percorsi adatti alle bici',discover:'Esplora percorsi',compare:'Percorsi disponibili',save:'Salva per dopo',saved:'Viaggi salvati',savedHere:'Salvati su questo dispositivo',emptySaved:'I viaggi salvati appariranno qui.',remove:'Rimuovi',start:'Parti ora',stop:'Termina viaggio',tripReady:'Pronto a partire',tripReadyHint:'Il percorso scelto è evidenziato. Salvalo o parti dalla tua posizione.',gpsWaiting:'Ricerca posizione…',gpsActive:'La tua posizione è sulla mappa. Segui il percorso e i segnali.',gpsDenied:'Posizione non disponibile. Consenti l’accesso nel browser.',gpsSecure:'La posizione live richiede HTTPS o localhost.',gpsNote:'Solo anteprima della posizione live. Nessun ricalcolo o guida vocale automatica.',instructions:'Indicazioni',instructionsFallback:'Le indicazioni per questa lingua sono disponibili in inglese.',savedMessage:'Viaggio salvato su questo dispositivo.',removedMessage:'Viaggio salvato rimosso.',savedLoaded:'Percorso salvato caricato. Controlla le condizioni prima di partire.',storageError:'Impossibile salvare il viaggio su questo dispositivo.',chooseFirst:'Scegli prima un percorso.',noExtra:'Nessun altro percorso diverso trovato per questo viaggio.',refresh:'Cerca di nuovo per condizioni aggiornate',selectedRoute:'Percorso scelto',arrival:'Arrivo a destinazione',kmAway:'{n} km alla destinazione',locationError:'Errore posizione: {error}',updated:'Aggiornato {time}',roadNotice:'Preferenza richiesta; il percorso può includere strade escluse.',navigationInfo:'Scegli un percorso, poi salvalo o parti ora.',mapAria:'Mappa del percorso',savedAria:'Percorsi salvati',resultsAria:'Percorsi disponibili'},
    fr:{hero:'Votre route, votre choix',intro:'Comparez de vrais trajets et choisissez celui qui vous convient.',tripType:'Comment voyagez-vous ?',drive:'Voiture',walk:'À pied',cycle:'Vélo',driveHint:'Trafic et préférences routières',walkHint:'Chemins et trottoirs',cycleHint:'Trajets adaptés au vélo',discover:'Explorer les trajets',compare:'Trajets disponibles',save:'Enregistrer pour plus tard',saved:'Trajets enregistrés',savedHere:'Enregistrés sur cet appareil',emptySaved:'Vos trajets enregistrés apparaîtront ici.',remove:'Supprimer',start:'Partir maintenant',stop:'Terminer le trajet',tripReady:'Prêt à partir',tripReadyHint:'Le trajet choisi est surligné. Enregistrez-le ou partez de votre position.',gpsWaiting:'Recherche de votre position…',gpsActive:'Votre position apparaît sur la carte. Suivez le trajet et les panneaux.',gpsDenied:'Position indisponible. Autorisez l’accès dans le navigateur.',gpsSecure:'La position en direct nécessite HTTPS ou localhost.',gpsNote:'Aperçu de position uniquement. Pas encore de recalcul ou de guidage vocal.',instructions:'Étapes du trajet',instructionsFallback:'Les instructions pour cette langue sont disponibles en anglais.',savedMessage:'Trajet enregistré sur cet appareil.',removedMessage:'Trajet enregistré supprimé.',savedLoaded:'Trajet enregistré chargé. Vérifiez les conditions actuelles avant de partir.',storageError:'Impossible d’enregistrer ce trajet sur cet appareil.',chooseFirst:'Choisissez d’abord un trajet.',noExtra:'Aucun autre trajet distinct trouvé.',refresh:'Rechercher à nouveau pour les conditions actuelles',selectedRoute:'Trajet choisi',arrival:'Arrivée à destination',kmAway:'{n} km jusqu’à destination',locationError:'Erreur de position : {error}',updated:'Actualisé {time}',roadNotice:'Préférence demandée ; certaines routes exclues peuvent rester.',navigationInfo:'Choisissez un trajet, puis enregistrez-le ou partez.',mapAria:'Carte du trajet',savedAria:'Trajets enregistrés',resultsAria:'Trajets disponibles'},
    nl:{hero:'Jouw route, jouw keuze',intro:'Vergelijk echte routes en kies de reis die bij je past.',tripType:'Hoe reis je?',drive:'Auto',walk:'Lopen',cycle:'Fiets',driveHint:'Verkeer en wegvoorkeuren',walkHint:'Paden en trottoirs',cycleHint:'Fietsvriendelijke routes',discover:'Routes ontdekken',compare:'Beschikbare routes',save:'Bewaar voor later',saved:'Opgeslagen ritten',savedHere:'Opgeslagen op dit apparaat',emptySaved:'Je opgeslagen ritten verschijnen hier.',remove:'Verwijderen',start:'Nu vertrekken',stop:'Rit stoppen',tripReady:'Klaar om te gaan',tripReadyHint:'Je gekozen route is gemarkeerd. Bewaar hem of vertrek vanaf je locatie.',gpsWaiting:'Locatie bepalen…',gpsActive:'Je locatie staat op de kaart. Volg de route en verkeersborden.',gpsDenied:'Locatie niet beschikbaar. Sta toegang toe in je browser.',gpsSecure:'Live locatie vereist HTTPS of localhost.',gpsNote:'Alleen live locatievoorbeeld. Nog geen automatische herberekening of spraakbegeleiding.',instructions:'Routeaanwijzingen',instructionsFallback:'Aanwijzingen voor deze taal zijn in het Engels beschikbaar.',savedMessage:'Rit opgeslagen op dit apparaat.',removedMessage:'Opgeslagen rit verwijderd.',savedLoaded:'Opgeslagen route geladen. Controleer actuele omstandigheden voor vertrek.',storageError:'Rit kon niet op dit apparaat worden opgeslagen.',chooseFirst:'Kies eerst een route.',noExtra:'Geen andere verschillende routes gevonden.',refresh:'Zoek opnieuw voor actuele omstandigheden',selectedRoute:'Gekozen route',arrival:'Aankomst op bestemming',kmAway:'{n} km tot bestemming',locationError:'Locatiefout: {error}',updated:'Bijgewerkt {time}',roadNotice:'Wegvoorkeur aangevraagd; uitgesloten wegen kunnen toch voorkomen.',navigationInfo:'Kies een route en bewaar hem of vertrek nu.',mapAria:'Routekaart',savedAria:'Opgeslagen routes',resultsAria:'Beschikbare routes'},
    fa:{hero:'مسیرت، انتخاب تو',intro:'مسیرهای واقعی را مقایسه کن و سفری را که دوست داری انتخاب کن.',tripType:'چطور می‌روی؟',drive:'ماشین',walk:'پیاده',cycle:'دوچرخه',driveHint:'ترافیک و ترجیح نوع جاده',walkHint:'مسیرهای پیاده‌روی',cycleHint:'مسیرهای مناسب دوچرخه',discover:'پیدا کردن مسیرها',compare:'مسیرهای موجود',save:'ذخیره برای بعد',saved:'سفرهای ذخیره‌شده',savedHere:'ذخیره‌شده روی همین دستگاه',emptySaved:'سفرهای ذخیره‌شده‌ات اینجا دیده می‌شوند.',remove:'حذف',start:'شروع سفر',stop:'پایان سفر',tripReady:'آمادهٔ حرکت',tripReadyHint:'مسیر انتخابی روی نقشه مشخص است. آن را ذخیره کن یا با موقعیت فعلی‌ات شروع کن.',gpsWaiting:'در حال پیدا کردن موقعیت تو…',gpsActive:'موقعیتت روی نقشه دیده می‌شود. مسیر و تابلوهای جاده را دنبال کن.',gpsDenied:'موقعیت در دسترس نیست. دسترسی مکان را در مرورگر فعال کن.',gpsSecure:'نمایش موقعیت زنده به HTTPS یا localhost نیاز دارد.',gpsNote:'فعلاً فقط موقعیت زنده نشان داده می‌شود؛ تغییر خودکار مسیر و راهنمای صوتی هنوز ندارد.',instructions:'مراحل مسیر',instructionsFallback:'راهنمای این مسیر به زبان انگلیسی ارائه می‌شود.',savedMessage:'سفر روی همین دستگاه ذخیره شد.',removedMessage:'سفر ذخیره‌شده حذف شد.',savedLoaded:'مسیر ذخیره‌شده باز شد. پیش از حرکت وضعیت روز را بررسی کن.',storageError:'این سفر روی دستگاه ذخیره نشد.',chooseFirst:'اول یک مسیر انتخاب کن.',noExtra:'برای این سفر مسیر متمایز دیگری پیدا نشد.',refresh:'جست‌وجوی دوباره برای وضعیت امروز',selectedRoute:'مسیر انتخابی',arrival:'رسیدن به مقصد',kmAway:'{n} کیلومتر تا مقصد',locationError:'خطای موقعیت: {error}',updated:'به‌روزرسانی {time}',roadNotice:'نوع جاده درخواست شده؛ ممکن است باز هم جادهٔ مستثناشده در مسیر باشد.',navigationInfo:'یک مسیر انتخاب کن؛ بعد ذخیره‌اش کن یا حرکت را شروع کن.',mapAria:'نقشهٔ مسیر',savedAria:'مسیرهای ذخیره‌شده',resultsAria:'مسیرهای موجود'}
  };
  for (const code of Object.keys(extra)) Object.assign(translations[code], extra[code]);
  const placeTexts = {
    en:{confirmFrom:'Select your exact starting place from the list.',confirmTo:'Select your exact destination from the list.',placeHelp:'Check the city and country before choosing.',placeNotFound:'No matching place found. Add the city and country to the address.',searchingPlaces:'Finding matching places…',placeSearchFailed:'Place search failed. Try a more complete address.'},
    de:{confirmFrom:'Wähle den genauen Startort aus der Liste.',confirmTo:'Wähle das genaue Ziel aus der Liste.',placeHelp:'Prüfe vor der Auswahl Ort und Land.',placeNotFound:'Kein passender Ort gefunden. Ergänze Ort und Land in der Adresse.',searchingPlaces:'Suche passende Orte…',placeSearchFailed:'Ortssuche fehlgeschlagen. Versuche eine vollständigere Adresse.'},
    it:{confirmFrom:'Scegli il punto di partenza esatto dalla lista.',confirmTo:'Scegli la destinazione esatta dalla lista.',placeHelp:'Controlla città e paese prima di scegliere.',placeNotFound:'Nessun luogo trovato. Aggiungi città e paese all’indirizzo.',searchingPlaces:'Ricerca dei luoghi…',placeSearchFailed:'Ricerca non riuscita. Prova un indirizzo più completo.'},
    fr:{confirmFrom:'Choisissez le point de départ exact dans la liste.',confirmTo:'Choisissez la destination exacte dans la liste.',placeHelp:'Vérifiez la ville et le pays avant de choisir.',placeNotFound:'Aucun lieu trouvé. Ajoutez la ville et le pays à l’adresse.',searchingPlaces:'Recherche des lieux…',placeSearchFailed:'Recherche échouée. Essayez une adresse plus complète.'},
    nl:{confirmFrom:'Kies de exacte vertrekplaats uit de lijst.',confirmTo:'Kies de exacte bestemming uit de lijst.',placeHelp:'Controleer plaats en land voordat je kiest.',placeNotFound:'Geen passende plaats gevonden. Voeg plaats en land toe.',searchingPlaces:'Plaatsen zoeken…',placeSearchFailed:'Zoeken mislukt. Probeer een vollediger adres.'},
    fa:{confirmFrom:'مبدأ دقیق را از فهرست انتخاب کن.',confirmTo:'مقصد دقیق را از فهرست انتخاب کن.',placeHelp:'قبل از انتخاب، شهر و کشور را بررسی کن.',placeNotFound:'مکان مناسب پیدا نشد. شهر و کشور را به آدرس اضافه کن.',searchingPlaces:'در حال پیدا کردن مکان‌ها…',placeSearchFailed:'جست‌وجوی مکان ناموفق بود. آدرس کامل‌تری وارد کن.'}
  };
  for (const code of Object.keys(placeTexts)) Object.assign(translations[code], placeTexts[code]);
  const voiceTexts = {
    en:{voiceOn:'Voice on',voiceOff:'Voice off',voiceUnavailable:'Voice unavailable in this browser',voiceNote:'Spoken steps are an experimental browser preview. Keep following road signs.',gpsNote:'Live location preview. Automatic rerouting is not available yet.'},
    de:{voiceOn:'Stimme an',voiceOff:'Stimme aus',voiceUnavailable:'Sprachausgabe in diesem Browser nicht verfügbar',voiceNote:'Gesprochene Hinweise sind eine Browser-Vorschau. Beachte weiterhin die Verkehrszeichen.',gpsNote:'Live-Standortvorschau. Automatische Neuberechnung ist noch nicht verfügbar.'},
    it:{voiceOn:'Voce attiva',voiceOff:'Voce disattivata',voiceUnavailable:'Voce non disponibile in questo browser',voiceNote:'Le istruzioni vocali sono un’anteprima nel browser. Segui sempre la segnaletica.',gpsNote:'Anteprima della posizione live. Il ricalcolo automatico non è ancora disponibile.'},
    fr:{voiceOn:'Voix activée',voiceOff:'Voix désactivée',voiceUnavailable:'Voix indisponible dans ce navigateur',voiceNote:'Les annonces vocales sont un aperçu dans le navigateur. Suivez toujours la signalisation.',gpsNote:'Aperçu de position en direct. Pas encore de recalcul automatique.'},
    nl:{voiceOn:'Stem aan',voiceOff:'Stem uit',voiceUnavailable:'Spraak niet beschikbaar in deze browser',voiceNote:'Gesproken aanwijzingen zijn een browservóórbeeld. Blijf verkeersborden volgen.',gpsNote:'Live locatievoorbeeld. Automatisch herberekenen is nog niet beschikbaar.'},
    fa:{voiceOn:'صدا روشن',voiceOff:'صدا خاموش',voiceUnavailable:'پخش صدا در این مرورگر در دسترس نیست',voiceNote:'راهنمای صوتی فعلاً نسخهٔ آزمایشی مرورگر است. تابلوهای مسیر را دنبال کن.',gpsNote:'موقعیت زنده نمایش داده می‌شود. تغییر خودکار مسیر هنوز فعال نیست.'}
  };
  for (const code of Object.keys(voiceTexts)) Object.assign(translations[code], voiceTexts[code]);
  const locationReadyTexts = {
    en:{useLocation:'Use my location',currentLocation:'Current location'},de:{useLocation:'Meinen Standort nutzen',currentLocation:'Aktueller Standort'},it:{useLocation:'Usa la mia posizione',currentLocation:'Posizione attuale'},fr:{useLocation:'Utiliser ma position',currentLocation:'Position actuelle'},nl:{useLocation:'Mijn locatie gebruiken',currentLocation:'Huidige locatie'},fa:{useLocation:'استفاده از موقعیت من',currentLocation:'موقعیت فعلی من'}
  };
  for (const code of Object.keys(locationReadyTexts)) Object.assign(translations[code], locationReadyTexts[code]);
  const tokenTexts = {
    en:{setupHint:'For local testing, paste a Mapbox public token beginning with pk. It stays in this browser on this device. For public deployment, use a restricted public token in config.js.',savedToken:'Public token saved in this browser. You can now search.'},
    de:{setupHint:'Zum lokalen Test einen öffentlichen Mapbox-Token einfügen, der mit pk. beginnt. Er bleibt in diesem Browser auf diesem Gerät. Für die Veröffentlichung einen eingeschränkten Token in config.js verwenden.',savedToken:'Öffentlicher Token in diesem Browser gespeichert. Du kannst jetzt suchen.'},
    it:{setupHint:'Per provare in locale, inserisci un token pubblico Mapbox che inizi con pk. Rimane in questo browser su questo dispositivo. Per pubblicare, usa un token pubblico limitato in config.js.',savedToken:'Token pubblico salvato nel browser. Ora puoi cercare.'},
    fr:{setupHint:'Pour tester en local, collez un jeton public Mapbox commençant par pk. Il reste dans ce navigateur sur cet appareil. Pour publier, utilisez un jeton public limité dans config.js.',savedToken:'Jeton public enregistré dans ce navigateur. Vous pouvez chercher.'},
    nl:{setupHint:'Plak voor lokaal testen een publieke Mapbox-token die met pk. begint. Deze blijft in deze browser op dit apparaat. Gebruik voor publicatie een beperkte publieke token in config.js.',savedToken:'Publieke token opgeslagen in deze browser. Je kunt nu zoeken.'},
    fa:{setupHint:'برای آزمایش، توکن عمومی Mapbox را که با pk. شروع می‌شود وارد کن. روی همین مرورگر و دستگاه می‌ماند. برای انتشار عمومی از توکن محدودشده در config.js استفاده کن.',savedToken:'توکن عمومی در این مرورگر ذخیره شد. حالا می‌توانی جست‌وجو کنی.'}
  };
  for (const code of Object.keys(tokenTexts)) Object.assign(translations[code], tokenTexts[code]);
  const durationAndVoiceTexts = {
    en:{durationHour:'{n} h',durationMinute:'{n} min',durationSecond:'{n} sec',voiceTest:'Test voice',voiceError:'Could not play voice. Check browser sound settings.',voiceNoSteps:'No spoken instruction is available for this route.'},
    de:{durationHour:'{n} Std.',durationMinute:'{n} Min.',durationSecond:'{n} Sek.',voiceTest:'Stimme testen',voiceError:'Sprachausgabe fehlgeschlagen. Prüfe die Toneinstellungen.',voiceNoSteps:'Für diese Strecke gibt es keinen Sprachhinweis.'},
    it:{durationHour:'{n} h',durationMinute:'{n} min',durationSecond:'{n} sec',voiceTest:'Prova la voce',voiceError:'Voce non riprodotta. Controlla l’audio del browser.',voiceNoSteps:'Nessuna istruzione vocale disponibile per questo percorso.'},
    fr:{durationHour:'{n} h',durationMinute:'{n} min',durationSecond:'{n} s',voiceTest:'Tester la voix',voiceError:'Lecture vocale impossible. Vérifiez le son du navigateur.',voiceNoSteps:'Aucune instruction vocale pour ce trajet.'},
    nl:{durationHour:'{n} u',durationMinute:'{n} min',durationSecond:'{n} sec',voiceTest:'Stem testen',voiceError:'Spraak afspelen mislukt. Controleer browsergeluid.',voiceNoSteps:'Geen gesproken aanwijzing voor deze route.'},
    fa:{durationHour:'{n} ساعت',durationMinute:'{n} دقیقه',durationSecond:'{n} ثانیه',voiceTest:'آزمایش صدا',voiceError:'صدا پخش نشد. تنظیمات صدای مرورگر را بررسی کن.',voiceNoSteps:'برای این مسیر راهنمای صوتی وجود ندارد.'}
  };
  for (const code of Object.keys(durationAndVoiceTexts)) Object.assign(translations[code], durationAndVoiceTexts[code]);
  const voiceReliabilityTexts = {
    en:{voiceSample:'In 200 meters, turn right.',voiceMissing:'No voice for this language is installed on this device. Add a system speech voice or choose another language.',voicePlaying:'Playing voice test…',voicePlayed:'Voice test finished.',instructionsRefresh:'These route instructions are still in the language used for the search. Search again to load them in the selected language.'},
    de:{voiceSample:'In 200 Metern rechts abbiegen.',voiceMissing:'Für diese Sprache ist keine Stimme auf dem Gerät installiert. Installiere eine Systemstimme oder wähle eine andere Sprache.',voicePlaying:'Sprachtest läuft…',voicePlayed:'Sprachtest beendet.',instructionsRefresh:'Diese Wegbeschreibung ist noch in der Sprache der Suche. Suche erneut, um sie in der gewählten Sprache zu laden.'},
    it:{voiceSample:'Tra 200 metri, gira a destra.',voiceMissing:'Nessuna voce per questa lingua installata sul dispositivo. Aggiungi una voce di sistema o scegli un’altra lingua.',voicePlaying:'Prova vocale in corso…',voicePlayed:'Prova vocale completata.',instructionsRefresh:'Le istruzioni sono ancora nella lingua della ricerca. Cerca di nuovo per caricarle nella lingua scelta.'},
    fr:{voiceSample:'Dans 200 mètres, tournez à droite.',voiceMissing:'Aucune voix pour cette langue n’est installée sur cet appareil. Ajoutez une voix système ou choisissez une autre langue.',voicePlaying:'Test vocal en cours…',voicePlayed:'Test vocal terminé.',instructionsRefresh:'Ces instructions sont encore dans la langue de la recherche. Relancez la recherche pour les charger dans la langue choisie.'},
    nl:{voiceSample:'Sla over 200 meter rechtsaf.',voiceMissing:'Er is geen stem voor deze taal op dit apparaat geïnstalleerd. Voeg een systeemstem toe of kies een andere taal.',voicePlaying:'Stemtest wordt afgespeeld…',voicePlayed:'Stemtest voltooid.',instructionsRefresh:'De aanwijzingen zijn nog in de taal van de zoekopdracht. Zoek opnieuw om ze in de gekozen taal te laden.'},
    fa:{voiceSample:'دویست متر دیگر به راست بپیچید.',voiceMissing:'صدایی برای این زبان روی دستگاه نصب نیست. صدای آن زبان را در تنظیمات سیستم نصب کن یا زبان دیگری انتخاب کن.',voicePlaying:'در حال پخش آزمایش صدا…',voicePlayed:'آزمایش صدا تمام شد.',instructionsRefresh:'راهنمای این مسیر هنوز به زبان زمان جست‌وجو است. برای دریافت زبان انتخابی دوباره جست‌وجو کن.'}
  };
  for (const code of Object.keys(voiceReliabilityTexts)) Object.assign(translations[code], voiceReliabilityTexts[code]);
  const guidanceTexts = {
    en:{nextManeuver:'In about {n} m: {instruction}',offRoute:'Your position is away from the chosen route. Return to the route; automatic rerouting is not available yet.',continueRoute:'Continue along the selected route.',voicePlayed:'The browser reports that the test ended. If you heard nothing, check this browser’s sound output.'},
    de:{nextManeuver:'In etwa {n} m: {instruction}',offRoute:'Dein Standort ist abseits der gewählten Strecke. Kehre zur Strecke zurück; automatische Neuberechnung gibt es noch nicht.',continueRoute:'Folge weiter der gewählten Strecke.',voicePlayed:'Der Browser meldet: Sprachtest beendet. Wenn du nichts gehört hast, prüfe die Tonausgabe des Browsers.'},
    it:{nextManeuver:'Tra circa {n} m: {instruction}',offRoute:'La tua posizione è lontana dal percorso scelto. Torna al percorso; il ricalcolo automatico non è disponibile.',continueRoute:'Continua sul percorso scelto.',voicePlayed:'Il browser segnala che il test è terminato. Se non hai sentito nulla, controlla l’audio del browser.'},
    fr:{nextManeuver:'Dans environ {n} m : {instruction}',offRoute:'Votre position est éloignée du trajet choisi. Revenez sur le trajet ; le recalcul automatique n’est pas disponible.',continueRoute:'Continuez sur le trajet choisi.',voicePlayed:'Le navigateur signale la fin du test. Si vous n’avez rien entendu, vérifiez sa sortie audio.'},
    nl:{nextManeuver:'Over ongeveer {n} m: {instruction}',offRoute:'Je positie ligt buiten de gekozen route. Ga terug naar de route; automatisch herberekenen is nog niet beschikbaar.',continueRoute:'Volg de gekozen route verder.',voicePlayed:'De browser meldt dat de test is afgelopen. Heb je niets gehoord, controleer dan het browsergeluid.'},
    fa:{nextManeuver:'حدود {n} متر دیگر: {instruction}',offRoute:'از مسیر انتخابی فاصله داری. به مسیر برگرد؛ محاسبهٔ دوبارهٔ مسیر هنوز فعال نیست.',continueRoute:'در مسیر انتخابی ادامه بده.',voicePlayed:'مرورگر اعلام کرد آزمایش صدا تمام شده است. اگر چیزی نشنیدی، خروجی صدای مرورگر را بررسی کن.'}
  };
  for (const code of Object.keys(guidanceTexts)) Object.assign(translations[code], guidanceTexts[code]);
  const voiceChoiceTexts = {
    en:{voiceChoose:'Voice for this language',voiceNone:'No voice available in this browser',voiceAuto:'Waiting for browser voices…',voiceMissing:'This browser does not offer a voice for this language.',voiceDialect:'This browser offers another Persian variety. Choose an Iranian Persian (fa-IR) voice here if one is available.'},
    de:{voiceChoose:'Stimme für diese Sprache',voiceNone:'Keine Stimme in diesem Browser verfügbar',voiceAuto:'Warte auf Browserstimmen…',voiceMissing:'Dieser Browser bietet keine Stimme für diese Sprache an.',voiceDialect:'Dieser Browser bietet eine andere persische Variante an. Wähle hier Persisch (Iran, fa-IR), falls verfügbar.'},
    it:{voiceChoose:'Voce per questa lingua',voiceNone:'Nessuna voce disponibile nel browser',voiceAuto:'In attesa delle voci del browser…',voiceMissing:'Questo browser non offre una voce per questa lingua.',voiceDialect:'Il browser offre un’altra varietà di persiano. Se disponibile, scegli persiano iraniano (fa-IR).'},
    fr:{voiceChoose:'Voix pour cette langue',voiceNone:'Aucune voix disponible dans ce navigateur',voiceAuto:'Chargement des voix du navigateur…',voiceMissing:'Ce navigateur ne propose pas de voix pour cette langue.',voiceDialect:'Ce navigateur propose une autre variété de persan. Choisissez persan d’Iran (fa-IR) si disponible.'},
    nl:{voiceChoose:'Stem voor deze taal',voiceNone:'Geen stem beschikbaar in deze browser',voiceAuto:'Wachten op browserstemmen…',voiceMissing:'Deze browser biedt geen stem voor deze taal.',voiceDialect:'Deze browser biedt een andere Perzische variant. Kies Iraans Perzisch (fa-IR) als die beschikbaar is.'},
    fa:{voiceChoose:'صدای این زبان',voiceNone:'صدای این زبان در این مرورگر در دسترس نیست',voiceAuto:'در حال دریافت صداهای مرورگر…',voiceMissing:'این مرورگر صدایی برای این زبان ارائه نمی‌کند.',voiceDialect:'این مرورگر گونهٔ دیگری از فارسی را دارد. اگر گزینهٔ fa-IR موجود است، آن را برای فارسی ایران انتخاب کن.'}
  };
  for (const code of Object.keys(voiceChoiceTexts)) Object.assign(translations[code], voiceChoiceTexts[code]);
  const locationTexts = {
    en:{locationReady:'Your location is set as the start (estimated accuracy: {n} m). Desktop location may be approximate.',locationRetry:'Precise location was unavailable; trying approximate location…',locationTimedOut:'Location timed out. Check Windows location settings, browser permission, and Wi-Fi, then try again.',locationUnavailable:'Location unavailable. Check Windows location settings and browser permission, then try again.'},
    de:{locationReady:'Dein Standort ist als Start gesetzt (geschätzte Genauigkeit: {n} m). Am Computer kann er ungenau sein.',locationRetry:'Genauer Standort nicht verfügbar; versuche ungefähren Standort…',locationTimedOut:'Standortsuche abgelaufen. Prüfe die Windows-Standorteinstellungen, Browserfreigabe und WLAN.',locationUnavailable:'Standort nicht verfügbar. Prüfe die Windows-Standorteinstellungen und Browserfreigabe.'},
    it:{locationReady:'Posizione impostata come partenza (precisione stimata: {n} m). Sul computer potrebbe essere approssimativa.',locationRetry:'Posizione precisa non disponibile; provo quella approssimativa…',locationTimedOut:'Ricerca posizione scaduta. Controlla le impostazioni di Windows, i permessi del browser e il Wi-Fi.',locationUnavailable:'Posizione non disponibile. Controlla le impostazioni di Windows e i permessi del browser.'},
    fr:{locationReady:'Position définie comme départ (précision estimée : {n} m). Sur ordinateur, elle peut être approximative.',locationRetry:'Position précise indisponible ; essai de position approximative…',locationTimedOut:'Délai de localisation dépassé. Vérifiez les paramètres Windows, les autorisations du navigateur et le Wi-Fi.',locationUnavailable:'Position indisponible. Vérifiez les paramètres Windows et les autorisations du navigateur.'},
    nl:{locationReady:'Je locatie is het vertrekpunt (geschatte nauwkeurigheid: {n} m). Op een computer kan dit bij benadering zijn.',locationRetry:'Nauwkeurige locatie niet beschikbaar; probeer een globale locatie…',locationTimedOut:'Locatie zoeken duurde te lang. Controleer Windows-locatie, browsertoestemming en wifi.',locationUnavailable:'Locatie niet beschikbaar. Controleer Windows-locatie en browsertoestemming.'},
    fa:{locationReady:'موقعیت فعلی به‌عنوان مبدأ ثبت شد (دقت تخمینی: {n} متر). روی کامپیوتر ممکن است تقریبی باشد.',locationRetry:'موقعیت دقیق پیدا نشد؛ موقعیت تقریبی را امتحان می‌کنم…',locationTimedOut:'زمان دریافت موقعیت تمام شد. مکان‌یابی ویندوز، اجازهٔ مرورگر و Wi-Fi را بررسی کن و دوباره بزن.',locationUnavailable:'موقعیت در دسترس نیست. مکان‌یابی ویندوز و اجازهٔ مرورگر را بررسی کن و دوباره بزن.'}
  };
  for (const code of Object.keys(locationTexts)) Object.assign(translations[code], locationTexts[code]);
  const routeVoiceTexts = {
    en:{instructionsLoading:'Loading directions in the selected language…',instructionsUpdated:'Route directions are ready in the selected language.',persianGuidanceUnavailable:'Live Persian turn-by-turn speech is not available yet. The route and current position remain visible; do not rely on English steps as Persian guidance.'},
    de:{instructionsLoading:'Lade Wegbeschreibung in der gewählten Sprache…',instructionsUpdated:'Die Wegbeschreibung ist in der gewählten Sprache bereit.',persianGuidanceUnavailable:'Persische Sprachführung ist noch nicht verfügbar. Strecke und Standort bleiben sichtbar.'},
    it:{instructionsLoading:'Caricamento delle indicazioni nella lingua scelta…',instructionsUpdated:'Indicazioni pronte nella lingua scelta.',persianGuidanceUnavailable:'La guida vocale in persiano non è ancora disponibile. Percorso e posizione restano visibili.'},
    fr:{instructionsLoading:'Chargement des instructions dans la langue choisie…',instructionsUpdated:'Les instructions sont prêtes dans la langue choisie.',persianGuidanceUnavailable:'Le guidage vocal en persan n’est pas encore disponible. Le trajet et la position restent visibles.'},
    nl:{instructionsLoading:'Routeaanwijzingen laden in de gekozen taal…',instructionsUpdated:'Routeaanwijzingen staan klaar in de gekozen taal.',persianGuidanceUnavailable:'Gesproken routebegeleiding in het Perzisch is nog niet beschikbaar. Route en locatie blijven zichtbaar.'},
    fa:{instructionsLoading:'در حال دریافت راهنمای مسیر به زبان انتخاب‌شده…',instructionsUpdated:'راهنمای مسیر به زبان انتخاب‌شده آماده شد.',persianGuidanceUnavailable:'راهنمای صوتی مرحله‌به‌مرحلهٔ فارسی هنوز آماده نیست. مسیر و موقعیت روی نقشه دیده می‌شوند؛ دستور انگلیسی را راهنمای فارسی فرض نکن.'}
  };
  for (const code of Object.keys(routeVoiceTexts)) Object.assign(translations[code], routeVoiceTexts[code]);
  const supported = Object.keys(translations);
  let storedLanguage;
  try { storedLanguage = localStorage.getItem('scout_language'); } catch { storedLanguage = null; }
  const initial = storedLanguage || navigator.language.slice(0, 2);
  let current = supported.includes(initial) ? initial : 'en';
  const t = (key, values = {}) => (translations[current][key] || translations.en[key] || key)
    .replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? ''));
  function applyLanguage() {
    document.documentElement.lang = current;
    document.documentElement.dir = current === 'fa' ? 'rtl' : 'ltr';
    document.querySelectorAll('[data-i18n]').forEach(el => { el.textContent = t(el.dataset.i18n); });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => { el.placeholder = t(el.dataset.i18nPlaceholder); });
    document.getElementById('language').value = current;
    document.title = 'Scout Lane AI | ' + t('choose');
  }
  function setLanguage(code) {
    if (!supported.includes(code)) return;
    current = code;
    try { localStorage.setItem('scout_language', code); } catch { /* Language still changes for this page. */ }
    applyLanguage();
    document.dispatchEvent(new CustomEvent('scout:language', {detail:{language:code}}));
  }
  window.ScoutI18n = {t, setLanguage, getLanguage: () => current};
  applyLanguage();
  document.getElementById('language').addEventListener('change', event => setLanguage(event.target.value));
})();
